apiVersion: apps/v1 
kind: Deployment
metadata:
  name: sample-deployment
spec:
  selector:
    matchLabels:
      app: sample
  replicas: 5 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample
        image: nirmala12345/demo:1.4
        ports:
        - containerPort: 80
---
# https://kubernetes.io/docs/concepts/s...  
kind: Service
apiVersion: v1
metadata:
  name: sample-service
spec:
  selector:
    app: sample
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000
  type: LoadBalancer
